framework:
    workflows:
        box_creation:
            type: 'state_machine'
            marking_store:
                type: 'single_state'
                arguments:
                    - 'status'
            supports:
                - App\Entity\Box
            initial_place: box_created
            places:
                - box_created
                - box_filled
                - validation
                - invalidated
                - go
            transitions:
                add_products:
                    from: box_created
                    to:   box_filled
                order_products:
                    from: box_filled
                    to:   validation
                validate:
                    from: validation
                    to:   go
                invalidate:
                    from: validation
                    to:   invalidated
                add_products_invalidated:
                    from: invalidated
                    to:   box_filled
