#index:
#    path: /
#    controller: App\Controller\DefaultController::index

admin:
    resource: ../src/Admin/config/routing.yaml
    # this prefix is added to all the action route names
    name_prefix: admin_
    # this prefix is added to all the action URLs
    prefix: /admin